name: Deploy to GitHub Pages

on:
  # This workflow is now only triggered manually
  # The main workflow now handles the artifact creation and upload
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Always run when manually triggered
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Create a placeholder artifact if none exists
      - name: Create placeholder artifact
        run: |
          mkdir -p artifact
          echo "<html><head><title>Zotero ArXiv Daily</title></head><body><h1>Zotero ArXiv Daily</h1><p>RSS feed will be available soon.</p></body></html>" > artifact/index.html
          echo "<?xml version='1.0' encoding='UTF-8'?><feed xmlns='http://www.w3.org/2005/Atom'><title>Zotero ArXiv Daily</title><subtitle>RSS feed will be available soon.</subtitle></feed>" > artifact/index.xml
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifact'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
