name: Deploy to GitHub Pages

on:
  # This workflow is now only triggered manually
  # The main workflow now handles the artifact creation and upload
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Always run when manually triggered
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # We no longer need to create content here as it's created in the main workflow
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
