name: Test workflow
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'
          
      - name: Install dependencies
        run: |
          uv venv && uv pip install .

      - name: Run script
        run: |
          source .venv/bin/activate
          python main.py --debug
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          ARXIV_QUERY: ${{ vars.ARXIV_QUERY }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MAX_PAPER_NUM: ${{ vars.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ vars.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
          MODEL_NAME: ${{ vars.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
          TRANSLATE_TITLE: ${{ vars.TRANSLATE_TITLE }}
          GENERATE_RSS: ${{ vars.GENERATE_RSS }}
          RSS_OUTPUT: ${{ vars.RSS_OUTPUT }}
          RSS_TITLE: ${{ vars.RSS_TITLE }}
          RSS_LINK: ${{ vars.RSS_LINK }}
          RSS_DESCRIPTION: ${{ vars.RSS_DESCRIPTION }}
          
      - name: Create artifact for GitHub Pages
        if: ${{ vars.GENERATE_RSS == 'true' }}
        run: |
          # Ensure the artifact directory exists
          mkdir -p gh-pages-artifact
          
          # Copy the RSS file to the artifact directory
          cp ${{ vars.RSS_OUTPUT || 'public/index.xml' }} gh-pages-artifact/index.xml
          
          # Create an index.html that redirects to the RSS feed
          echo "<html><head><meta http-equiv='refresh' content='0;url=index.xml'></head><body><h1>Zotero ArXiv Daily</h1><p>Redirecting to <a href='index.xml'>RSS feed</a>...</p></body></html>" > gh-pages-artifact/index.html
      
      - name: Upload Pages artifact
        if: ${{ vars.GENERATE_RSS == 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: './gh-pages-artifact'
