name: Test workflow
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '**.md'
      - '.github/FUNDING.yml'
      - 'LICENSE'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          ARXIV_QUERY: ${{ vars.ARXIV_QUERY }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MAX_PAPER_NUM: ${{ vars.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ vars.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
          MODEL_NAME: ${{ vars.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
          TRANSLATE_TITLE: ${{ vars.TRANSLATE_TITLE }}
          # RSS feed 相关配置
          GENERATE_RSS: ${{ vars.GENERATE_RSS }}
          RSS_OUTPUT: ${{ vars.RSS_OUTPUT }}
          RSS_TITLE: ${{ vars.RSS_TITLE }}
          RSS_LINK: ${{ vars.RSS_LINK }}
          RSS_DESCRIPTION: ${{ vars.RSS_DESCRIPTION }}
        run: |
          uv run main.py --debug
